version: '2'

# Define the services/containers to be run
services:
  devRuntime: #name of your service
    image: 19962711/sep-slitherin:devRuntime # specify the directory of the Dockerfile
    ports:
      - "3001:3001" #specify ports forwarding
    links:
      - devDatabase # link this service to the database service
    depends_on:
      - devDatabase
      
    devDatabase: # name of the service
    image: mongo # specify image to build container from
    ports:
      - "27018:27017"

  configfrontend:
    image: 19962711/sep-slitherin:devFrontend
    ports:
      - "8082:8082"
    links:
      - devRuntime  
    depends_on:
      - devRuntime   