version: '2'

# Define the services/containers to be run
services:
  runtime: #name of your service
    build: ./backend/ # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forwarding
    links:
      - database
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - database
      
  database: # name of the service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017"

  frontend:
    build: ./frontend/
    ports:
      - "8080:8082"
    depends_on:
      - runtime   